In [ ]:
np.sum(np.diff(x) * (y[:-1] + np.diff(y)/2))

In [2]:
import numpy as np

In [196]:
class Preferences(object):
    def __init__(self):
        self['end'] = 0
        self['endValue'] = 0
        self.id = 0
        self['start'] = 0
        self['startValue'] = 0

In [197]:
#row is agent, column is slice
preferences = [[Preferences() for i in range(3)] for j in range(4)]

In [198]:
preferences[0][0]['end'] = 1
preferences[0][0]['endValue'] = 3.7
preferences[0][0].id = 1
preferences[0][0]['start'] = 0
preferences[0][0]['startValue'] = 5.8

In [199]:
preferences[0][1]['end'] = 2
preferences[0][1]['endValue'] = 5.5
preferences[0][1].id = 2
preferences[0][1]['start'] = 1
#preferences[0][1]['startValue'] = 5.5
preferences[0][1]['startValue'] = 9.6

In [200]:
preferences[0][2]['end'] = 3
preferences[0][2]['endValue'] = 7
preferences[0][2].id = 3
preferences[0][2]['start'] = 2
preferences[0][2]['startValue'] = 1.6

In [201]:
preferences[1][0]['end'] = 1
preferences[1][0]['endValue'] = 7.3
preferences[1][0].id = 4
preferences[1][0]['start'] = 0
preferences[1][0]['startValue'] = 3

In [202]:
preferences[1][1]['end'] = 2
preferences[1][1]['endValue'] = 7.5
preferences[1][1].id = 5
preferences[1][1]['start'] = 1
preferences[1][1]['startValue'] = 3

In [203]:
preferences[1][2]['end'] = 3
preferences[1][2]['endValue'] = 0
preferences[1][2].id = 6
preferences[1][2]['start'] = 2
preferences[1][2]['startValue'] = 10

In [204]:
preferences[2][0]['end'] = 1
preferences[2][0]['endValue'] = 4.3
preferences[2][0].id = 7
preferences[2][0]['start'] = 0
preferences[2][0]['startValue'] = 9.4

In [205]:
preferences[2][1]['end'] = 3
preferences[2][1]['endValue'] = 7.6
preferences[2][1].id = 8
preferences[2][1]['start'] = 1
#preferences[2][1]['startValue'] = 7.6
preferences[2][1]['startValue'] = 3

In [206]:
preferences[2][2] = None

In [207]:
preferences[3][0]['end'] = 3
preferences[3][0]['endValue'] = 3.8
preferences[3][0].id = 9
preferences[3][0]['start'] = 0
preferences[3][0]['startValue'] = 9.6

In [208]:
preferences[3][1] = None

In [209]:
preferences[3][2] = None

In [16]:
cakeSize = 3

In [210]:
#prefs, normalizationConstant = oneLipschitz(preferences, cakeSize)
preferences = one_lipschitz(preferences, cakeSize)

In [64]:
value

1.0000000000000002

In [69]:
value_query(0, preferences, 0, 1, epsilon)

0.5025000000000001

In [98]:
epsilon = 0.00025

Preprocessing

Hungriness:

In [2]:
def hollender_rubinstein(prefs, cakeSize, epsilon):
    #prefs = one_lipschitz(prefs, cakeSize)
    equipartition, alpha_lower_bound = compute_equipartition(prefs, 4, epsilon)
    if check_equipartition_envy_free_four_agents(prefs, alpha_lower_bound, 4,
                                                 epsilon) == True:
        return equipartition
    alpha_upper_bound = 1
    alpha_bounds = Bounds(alpha_lower_bound, alpha_upper_bound)
    x = 0
    while abs(alpha_bounds.upper - alpha_bounds.lower) > ((epsilon/10)**4)/12:
        alpha = alpha_bounds.midpoint()
        if check_invariant_four_agents(prefs, alpha, epsilon) == True:
            alpha_bounds.lower = alpha
        else:
            alpha_bounds.upper = alpha
        x = x  + 1
        if x < 50:
            print(alpha)
    return check_invariant_four_agents(prefs, alpha_bounds.lower, epsilon,
                                       return_division = True)
        

In [3]:
def branzei_nisan(prefs, cakeSize, epsilon):
    #prefs = one_lipschitz(prefs, cakeSize)
    equipartition, alpha_lower_bound = compute_equipartition(prefs, 3, epsilon)
    if check_equipartition_envy_free_three_agents(prefs, alpha_lower_bound, 3,
                                                  epsilon) == True:
        return equipartition
    alpha_upper_bound = 1
    alpha_bounds = Bounds(alpha_lower_bound, alpha_upper_bound)
    while abs(alpha_bounds.upper - alpha_bounds.lower) > ((epsilon/10)**4)/12:
        alpha = alpha_bounds.midpoint()
        if check_invariant_three_agents(prefs, alpha, epsilon)[0] == True:
            alpha_bounds.lower = alpha
        else:
            alpha_bounds.upper = alpha
    return division_three_agents(prefs, alpha_bounds.lower, epsilon)

In [247]:
equipartition, alpha_lower_bound = compute_equipartition(preferences, 4, epsilon)

In [252]:
equipartition.left, equipartition.middle, equipartition.right

(0.2813470448638227, 0.4683712301597646, 0.6948479654796877)

In [248]:
slice_values(0, preferences, equipartition, 4, epsilon)

array([0.125625, 0.125625, 0.125625, 0.125625])

In [249]:
slice_values(1, preferences, equipartition, 4, epsilon)

array([0.13264574, 0.08718211, 0.14586006, 0.13681208])

In [250]:
slice_values(2, preferences, equipartition, 4, epsilon)

array([0.17598466, 0.06169316, 0.09232022, 0.17250196])

In [251]:
slice_values(3, preferences, equipartition, 4, epsilon)

array([0.18513428, 0.10410993, 0.10580483, 0.10745096])

In [163]:
equipartition.left

0.24050704225352004

In [161]:
alpha_lower_bound

0.12562499999999951

In [261]:
division = hollender_rubinstein(preferences, cakeSize, epsilon)

0.5628124999999993
0.34421874999999896
0.28656784459693996,0.28656784459693996
0.24065705654264985,0.24065705654264985
0.44607347861488433,0.4531206744969431,0.9543978040882108
b
0.24065705654264985,0.24065705654264985
0.28656784459693996,0.28656784459693996
0.44607347861488433,0.4531206744969431,0.9543978040882108
b
0.27803630075379926,0.27803630075379926
0.2513270816020099,0.2513270816020099
0.44607347861488433,0.47718996285830934,0.9839174308875136
b
0.2513270816020099,0.2513270816020099
0.27803630075379926,0.27803630075379926
0.44607347861488433,0.47718996285830934,0.9839174308875136
b
0.28316936435618045,0.28316936435618045
0.24570343863879984,0.24570343863879984
0.44607347861488433,0.46397314465185574,0.96811150184574
b
0.24570343863879984,0.24570343863879984
0.28316936435618045,0.28316936435618045
0.44607347861488433,0.46397314465185574,0.96811150184574
b
0.23492187499999878
0.1802734374999987
0.15294921874999867
0.15311322565038205,0.15311322565038205
0.15571202707467052,0.1557

In [264]:
len(preferences)

4

In [269]:
array_of_dicts =  [
        [
            {
                "start": 0,
                "startValue": 6.6,
                "end": 1,
                "endValue": 6.6,
                "id": 1
            },
            {
                "start": 1,
                "startValue": 9.1,
                "end": 2,
                "endValue": 9.1,
                "id": 2
            }
        ],
        [
            {
                "start": 0,
                "startValue": 5.4,
                "end": 1,
                "endValue": 5.4,
                "id": 3
            },
            {
                "start": 1,
                "startValue": 6.9,
                "end": 2,
                "endValue": 6.9,
                "id": 4
            }
        ],
        [
            {
                "start": 0,
                "startValue": 5.4,
                "end": 1,
                "endValue": 5.4,
                "id": 3
            },
            {
                "start": 1,
                "startValue": 6.9,
                "end": 2,
                "endValue": 6.9,
                "id": 4
            }
        ],
        [
            {
                "start": 0,
                "startValue": 5.4,
                "end": 1,
                "endValue": 5.4,
                "id": 3
            },
            {
                "start": 1,
                "startValue": 6.9,
                "end": 2,
                "endValue": 6.9,
                "id": 4
            }
        ]
    ]

In [272]:
array_of_dicts[0][0]["start"]

0

In [268]:
array_of_dicts

NameError: name 'array_of_dicts' is not defined

In [4]:
preference_check =     [
        [
            {
                "start": 0,
                "startValue": 8.3,
                "end": 1,
                "endValue": 3,
                "id": 1
            },
            {
                "start": 1,
                "startValue": 3.3,
                "end": 2,
                "endValue": 10,
                "id": 2
            },
            {
                "start": 2,
                "startValue": 10,
                "end": 3,
                "endValue": 0.3,
                "id": 3
            }
        ],
        [
            {
                "start": 0,
                "startValue": 6.1,
                "end": 2,
                "endValue": 1.5,
                "id": 4
            },
            {
                "start": 2,
                "startValue": 6.9,
                "end": 3,
                "endValue": 3.7,
                "id": 5
            }
        ],
        [
            {
                "start": 0,
                "startValue": 2.1,
                "end": 1,
                "endValue": 8,
                "id": 6
            },
            {
                "start": 1,
                "startValue": 3.6,
                "end": 2,
                "endValue": 7.3,
                "id": 7
            },
            {
                "start": 2,
                "startValue": 2.2,
                "end": 3,
                "endValue": 5.4,
                "id": 8
            }
        ],
        [
            {
                "start": 0,
                "startValue": 8.7,
                "end": 1,
                "endValue": 3.7,
                "id": 9
            },
            {
                "start": 1,
                "startValue": 7.1,
                "end": 2,
                "endValue": 10,
                "id": 10
            },
            {
                "start": 2,
                "startValue": 6.9,
                "end": 3,
                "endValue": 1.9,
                "id": 11
            }
        ]
    ]

In [108]:
epsilon = 0.0025

In [95]:
preference_check = one_lipschitz(preference_check, 3)

In [106]:
division_check = FourAgentPortion(0.2449214685830472,0.4988810378964621,0.683353755888906)

In [109]:
slice_values(0, preference_check, division_check, 4, epsilon)

array([0.13436191, 0.09941426, 0.13436191, 0.13436191])

In [174]:
slice_values(0, preference_check, division_check, 4, epsilon / 10)

array([0.13381096, 0.09884141, 0.13394991, 0.13364772])

In [110]:
slice_values(1, preference_check, division_check, 4, epsilon)

array([0.15027123, 0.10499052, 0.05425255, 0.1929857 ])

In [111]:
slice_values(2, preference_check, division_check, 4, epsilon)

array([0.11025051, 0.14604046, 0.11654207, 0.12966697])

In [112]:
slice_values(3, preference_check, division_check, 4, epsilon)

array([0.13227677, 0.13225594, 0.13114762, 0.10681966])

In [173]:
slice_values(3, preference_check, division_check, 4, epsilon/ 100)

array([0.13167071, 0.13162675, 0.1306924 , 0.10603514])

In [167]:
ass = assign_slices(division_check, preference_check, epsilon, 4)

In [172]:
ass[0]

3

In [124]:
agents = [0,1,2,3]
agent = 1
agents.index(agent)

1

In [117]:
def assign_four_agents(division, prefs, epsilon):
    agents = [0,1,2,3]
    slices = [1,2,3,4]
    for i in range(agents_number):
        agent_slice_values[k] = slice_values(k, prefs, division, 4, epsilon)
    while np.size(agents) > 1:
        difference_between_top_two_slices = np.zeros(np.size(agents))
        for j in agents:
            best_value = np.max(agent_slice_values[k])
            best_value_position = np.argmax(agent_slice_values[k])
            remaining_values = np.delete(agent_slice_values[k], best_value_position)
            second_best_value = np.max(remaining_values)
            difference_between_top_two_slices[j] = \
                best_value - second_best_value
        agent
    

In [8]:
from scipy.optimize import linear_sum_assignment
import numpy as np

In [31]:
cost = np.array([[0, 0.00025, 0.2], [0, 0.55 * 0.00025, 1.1 * 0.00025], [0, 0.2* 0.00025, 0.00025]])
#cost = np.array([[0, 0.00025, 10000], [0, 0.55 * 0.00025, 10000], [0, 0.2* 0.00025, 0.00025]])
row_ind, col_ind = linear_sum_assignment(cost)
col_ind
#row_ind
#cost[row_ind, col_ind]

array([0, 2, 1], dtype=int64)

In [6]:
algorithm.find_matching(G, matching_type = 'max', return_type = 'list')

False

In [131]:
import pandas as pd

In [166]:
def assign_slices(division, prefs, epsilon, agents_number):
    if agents_number == 3:
        agents = [0,1,2]
        slices = [1,2,3]
    if  agents_number == 4:
        agents = [0,1,2,3]
        slices = [1,2,3,4]
    agent_slice_values = np.zeros((len(agents),len(slices)))
    for i in range(agents_number):
        agent_slice_values[i] = slice_values(i, prefs, division, agents_number, epsilon)
    assignments = {}  # To store the assignments of slices to agents

    while len(agents) > 1:
        max_difference = -1
        chosen_agent = None
        chosen_slice = None

        # Find the agent with the maximum difference between their top two best slices
        for agent in agents:
            # Sort the agent's valuations and get the indices of the top two values
            valuations = pd.DataFrame({"slices": slices,
                                       "values": agent_slice_values[agent]})
            sorted_valuations = valuations.sort_values(by ='values' , ascending=False).reset_index(drop=True)
            top_value = sorted_valuations["values"][0]
            second_value = sorted_valuations["values"][1]
            difference = top_value - second_value
            value_for_print = sorted_valuations["slices"][0]

            if difference > max_difference:
                max_difference = difference
                chosen_agent = agent
                chosen_slice = sorted_valuations["slices"][0]

        # Assign the chosen slice to the chosen agent
        assignments[chosen_agent] = chosen_slice

        # Remove the chosen agent and slice
        agents.remove(chosen_agent)
        slice_index = slices.index(chosen_slice)
        slices.remove(chosen_slice)
        agent_slice_values = [np.concatenate([val[:slice_index], val[slice_index+1:]]) for val in agent_slice_values]

    # Assign the remaining slice to the remaining agent
    assignments[agents[0]] = slices[0]

    return assignments

In [161]:
len([1,2,3])
[1,2,3][:0] 

[]

In [327]:
agents = [0,1,2,3]
slices = [1,2,3,4]
for i in range(agents_number):
    agent_slice_values[i] = slice_values(i, preference_check, 
                                         division_check, 4, epsilon)

agent_idx = agents.index(0)
sorted_valuations = sorted(agent_slice_values[agent_idx], reverse=True)

In [328]:
sorted_valuations

[0.13436191377708412,
 0.13436191377708395,
 0.1343619137770839,
 0.09941425866874534]

In [4]:
list  = [0,1,2,3,4]
x = np.delete(list, 1)
x

array([0, 2, 3, 4])

In [324]:
list = []
np.append(list,1)

array([1.])

In [323]:
agents = [1,2,3,4]
np.size(agents)

4

In [320]:
list[1:4]

[2]

In [266]:
check

array([1.31574045e-16, 1.30463822e-16, 1.30463822e-16, 6.83075530e-17])

In [ ]:
np.isclose(

In [185]:
left = division.left

In [186]:
left

0.2552773263205004

In [187]:
middle = division.middle

In [188]:
middle

0.5438978467132525

In [189]:
right = division.right

In [190]:
right

0.7390051901348342

In [191]:
slice_values(0, preferences, division, 4, epsilon)

array([0.13211572, 0.15186651, 0.15186651, 0.13211572])

In [ ]:
[
    {
        "owner": 0,
        "percentValues": [
            0.5,
            0.49120160884866776
        ],
        "edges": [
            [
                0,
                1.4411764705882355
            ]
        ]
    },
    {
        "owner": 1,
        "percentValues": [
            0.49999999999999983,
            0.5087983911513322
        ],
        "edges": [
            [
                1.4411764705882355,
                3
            ]
        ]
    }
]

In [ ]:
[
    {
        "actor": 0,
        "action": "judges the middle of the resource to be 48.0%",
        "pieces": [],
        "assign": false
    },
    {
        "actor": 0,
        "action": "cut the resource into two pieces at 48.0%",
        "pieces": [
            {
                "start": 0,
                "end": 1.4411764705882355,
                "values": [
                    11.55,
                    11.494117647058825
                ],
                "id": 1
            },
            {
                "start": 1.4411764705882355,
                "end": 3,
                "values": [
                    11.549999999999997,
                    11.905882352941173
                ],
                "id": 2
            }
        ],
        "assign": false
    },
    {
        "actor": 1,
        "action": "chooses piece 2 because it is worth 50.9% of the resource to them",
        "pieces": [
            {
                "start": 1.4411764705882355,
                "end": 3,
                "values": [
                    11.549999999999997,
                    11.905882352941173
                ],
                "id": 2
            }
        ],
        "assign": true
    },
    {
        "actor": 0,
        "action": "takes remaining piece",
        "pieces": [
            {
                "start": 0,
                "end": 1.4411764705882355,
                "values": [
                    11.55,
                    11.494117647058825
                ],
                "id": 1
            }
        ],
        "assign": true
    }
]

In [192]:
slice_values(1, preferences, division, 4, epsilon)

array([0.11617325, 0.1430743 , 0.1430743 , 0.10017815])

In [193]:
slice_values(2, preferences, division, 4, epsilon)

array([0.12996325, 0.13558858, 0.13558858, 0.13558858])

In [194]:
slice_values(3, preferences, division, 4, epsilon)

array([0.16942011, 0.15757566, 0.15757566, 0.08940828])

In [96]:
division = branzei_nisan(preferences, cakeSize, epsilon)

In [202]:
left = division.left

In [203]:
right = division.right

In [64]:
slice_values(0, preferences, division, 3, epsilon)

array([0.17312526, 0.17312526, 0.15624948])

In [97]:
slice_values(0, preferences, division, 3, epsilon)

array([0.17312526, 0.17312526, 0.15624948])

In [309]:
slice_values(1, preferences, division, epsilon)

array([0.17289765, 0.15670471, 0.17289765])

In [94]:
slice_values(1, preferences, division, 3, epsilon)

array([0.17289765, 0.15670471, 0.17289765])

In [310]:
slice_values(2, preferences, division, epsilon)

array([0.16442819, 0.15792471, 0.1801471 ])

In [95]:
slice_values(2, preferences, division, 3, epsilon)

array([0.16442819, 0.15792471, 0.1801471 ])

In [314]:
value_query_initial(0, preferences, 0, left), value_query_initial(0, preferences, left, right), value_query_initial(0, preferences, right, 1)

(0.34450429443207714, 0.3447305694920399, 0.3107651360758832)

In [204]:
value_query_initial(0, preferences, 0, left), value_query_initial(0, preferences, left, right), value_query_initial(0, preferences, right, 1)

(0.33330316332533366, 0.3335294383853035, 0.33316739828936304)

In [315]:
value_query_initial(1, preferences, 0, left), value_query_initial(1, preferences, left, right), value_query_initial(1, preferences, right, 1)

(0.3440473367594753, 0.31188949331914784, 0.34406316992137675)

In [205]:
value_query_initial(1, preferences, 0, left), value_query_initial(1, preferences, left, right), value_query_initial(1, preferences, right, 1)

(0.3379898246877153, 0.2902955777515832, 0.37171459756070135)

In [318]:
value_query_initial(2, preferences, 0, left), value_query_initial(2, preferences, left, right), value_query_initial(2, preferences, right, 1)

(0.32711016184950803, 0.31432946917691007, 0.3585603689735818)

In [206]:
value_query_initial(2, preferences, 0, left), value_query_initial(2, preferences, left, right), value_query_initial(2, preferences, right, 1)

(0.3168968361205145, 0.30411614344792287, 0.3789870204315625)

In [317]:
1,2,3

(1, 2, 3)

In [281]:
x = True, 2

In [298]:
check_invariant_three_agents(preferences, 0.3, epsilon)

False

In [282]:
x[0]

True

In [104]:
cutBounds = find_left_cut_bounds(preferences, epsilon)

In [78]:
cutBounds.upper

0.33984375

In [81]:
cutBounds = Bounds(0.34,0.3425)

In [105]:
left = cutBounds.midpoint()
value_query(0,preferences, 0, left, epsilon) / value_query(0,preferences, left, 1, epsilon)

0.49872568446745874

In [106]:
value_query(0,preferences, 0, 1, epsilon)

0.5025000000000001

In [83]:
cutBounds = find_right_cut_bounds(preferences, epsilon)

In [89]:
cutBounds.upper

0.634765625

In [96]:
cutBounds = Bounds(0.6325,0.635)

In [97]:
right = cutBounds.midpoint()
value_query(0,preferences, right, 1, epsilon) / value_query(0,preferences, 0, right, epsilon)

0.49931093178343766

In [66]:
check = Bounds(0.6344324880074275, 0.6344324880074286)

In [38]:
check.midpoint()

0.634432488007428

In [67]:
check.midpoint()

0.634432488007428

In [322]:
equipartition, alpha = compute_equipartition_three_agents(preferences, epsilon)

In [323]:
left = equipartition.left
right = equipartition.right

In [324]:
one = value_query(0, preferences, 0, left, epsilon)
two = value_query(0, preferences, left, right, epsilon)
three = value_query(0, preferences, right, 1, epsilon)

In [214]:
one/two

1.0000000000000075

In [325]:
one/two

1.0000000000000075

In [215]:
one/three

0.9999999999999959

In [216]:
two/three

0.9999999999999885

In [5]:
def check_invariant_four_agents(prefs, alpha, epsilon, return_division = False):
    if check_condition_a(prefs, alpha, epsilon) == True:
        return check_condition_a(prefs, alpha, epsilon, return_division)
    elif check_condition_b(prefs, alpha, epsilon) == True:
        return check_condition_b(prefs, alpha, epsilon, return_division)
    else:
        return False

In [6]:
def check_condition_a(prefs, alpha, epsilon, return_division = False):
    if condition_a_slice_one_preferred(prefs, alpha, epsilon) == True:
        return condition_a_slice_one_preferred(prefs, alpha, epsilon, return_division)
    if condition_a_slice_two_preferred(prefs, alpha, epsilon) == True:
        return condition_a_slice_two_preferred(prefs, alpha, epsilon, return_division)
    if condition_a_slice_three_preferred(prefs, alpha, epsilon) == True:
        return condition_a_slice_three_preferred(prefs, alpha, epsilon, return_division)
    if condition_a_slice_four_preferred(prefs, alpha, epsilon) == True:
        return condition_a_slice_four_preferred(prefs, alpha, epsilon, return_division)
    else:
        return False

In [7]:
def check_condition_b(prefs, alpha, epsilon, return_division = False):
    if condition_b_adjacent_slices_preferred(prefs, alpha, epsilon) == True:
        return condition_b_adjacent_slices_preferred(prefs, alpha, epsilon, return_division)
    if condition_b_one_apart_slices_preferred(prefs, alpha, epsilon) == True:
        return condition_b_one_apart_slices_preferred(prefs, alpha, epsilon, return_division)
    if condition_b_two_apart_slices_preferred(prefs, alpha, epsilon) == True:
        return condition_b_two_apart_slices_preferred(prefs, alpha, epsilon, return_division)
    else:
        return False

In [8]:
def condition_b_adjacent_slices_preferred(prefs, alpha, epsilon, return_division = False):
    if condition_b_slice_one_two_preferred(prefs, alpha, epsilon) == True:
        return condition_b_slice_one_two_preferred(prefs, alpha, epsilon, return_division)
    if condition_b_slice_two_three_preferred(prefs, alpha, epsilon) == True:
        return condition_b_slice_two_three_preferred(prefs, alpha, epsilon, return_division)
    if condition_b_slice_three_four_preferred(prefs, alpha, epsilon) == True:
        return condition_b_slice_three_four_preferred(prefs, alpha, epsilon, return_division)
    else:
        return False

In [9]:
def condition_b_one_apart_slices_preferred(prefs, alpha, epsilon, return_division = False):
    if condition_b_slice_one_three_preferred(prefs, alpha, epsilon) == True:
        return condition_b_slice_one_three_preferred(prefs, alpha, epsilon, return_division)
    if condition_b_slice_two_four_preferred(prefs, alpha, epsilon) == True:
        return condition_b_slice_two_four_preferred(prefs, alpha, epsilon, return_division)
    else:
        return False

In [10]:
def condition_b_two_apart_slices_preferred(prefs, alpha, epsilon, return_division = False):
    if condition_b_slice_one_four_preferred(prefs, alpha, epsilon) == True:
        return condition_b_slice_one_four_preferred(prefs, alpha, epsilon, return_division)
    else:
        return False

In [11]:
def condition_a_slice_one_preferred(prefs, alpha, epsilon, return_division = False):
    right_cut = cut_query(0, prefs, 1, alpha, epsilon, end_cut = False)
    middle_cut = cut_query(0, prefs, right_cut, alpha, epsilon, end_cut = False)
    left_cut = cut_query(0, prefs, middle_cut, alpha, epsilon, end_cut = False)
    division = FourAgentPortion(left_cut, middle_cut, right_cut)
    if check_valid_division(division) == False:
        return False
    check_value = condition_a_check(1, prefs, alpha, division, epsilon)
    if (check_value == True) and (return_division == True):
        return division
    else:
        return check_value
    

In [12]:
def condition_a_slice_two_preferred(prefs, alpha, epsilon, return_division = False):
    left_cut = cut_query(0, prefs, 0, alpha, epsilon, end_cut = True)
    right_cut = cut_query(0, prefs, 1, alpha, epsilon, end_cut = False)
    middle_cut = cut_query(0, prefs, right_cut, alpha, epsilon, end_cut = False)
    division = FourAgentPortion(left_cut, middle_cut, right_cut)
    if check_valid_division(division) == False:
        return False
    check_value = condition_a_check(2, prefs, alpha, division, epsilon)
    if (check_value == True) and (return_division == True):
        return division
    else:
        return check_value

In [13]:
def condition_a_slice_three_preferred(prefs, alpha, epsilon, return_division = False):
    left_cut = cut_query(0, prefs, 0, alpha, epsilon, end_cut = True)
    middle_cut = cut_query(0, prefs, left_cut, alpha, epsilon, end_cut = True)
    right_cut = cut_query(0, prefs, 1, alpha, epsilon, end_cut = False)
    division = FourAgentPortion(left_cut, middle_cut, right_cut)
    if check_valid_division(division) == False:
        return False
    check_value = condition_a_check(3, prefs, alpha, division, epsilon)
    if (check_value == True) and (return_division == True):
        return division
    else:
        return check_value

In [14]:
def condition_a_slice_four_preferred(prefs, alpha, epsilon, return_division = False):
    left_cut = cut_query(0, prefs, 0, alpha, epsilon, end_cut = True)
    middle_cut = cut_query(0, prefs, left_cut, alpha, epsilon, end_cut = True)
    right_cut = cut_query(0, prefs, middle_cut, alpha, epsilon, end_cut = True)
    division = FourAgentPortion(left_cut, middle_cut, right_cut)
    if check_valid_division(division) == False:
        return False
    check_value = condition_a_check(4, prefs, alpha, division, epsilon)
    if (check_value == True) and (return_division == True):
        return division
    else:
        return check_value

In [15]:
def condition_a_check(slice, prefs, alpha, division, epsilon):
    agents_number = 4
    slices_number = 4
    agent_slice_values = np.zeros((agents_number,slices_number))
    for k in range(agents_number):
        agent_slice_values[k] = slice_values(k, prefs, division, 4, epsilon)
    for i in range(1, agents_number):
        for j in range(1, agents_number):
            if j == i:
                continue
            if ((agent_slice_values[i][slice-1] == np.max(agent_slice_values[i])) and \
                (agent_slice_values[j][slice-1] == np.max(agent_slice_values[j])) and \
                (agent_slice_values[0][slice-1] <= alpha)):
                return True
            else:
                return False

In [16]:
def condition_a_check(slice, prefs, alpha, division, epsilon):
    agents_number = 4
    slices_number = 4
    agent_slice_values = np.zeros((agents_number,slices_number))
    for k in range(agents_number):
        agent_slice_values[k] = slice_values(k, prefs, division, 4, epsilon)
    for i in range(1, agents_number):
        for j in range(1, agents_number):
            if j == i:
                continue
            if (np.isclose(agent_slice_values[i][slice-1], np.max(agent_slice_values[i]),rtol=0,atol=1e-10) and \
                np.isclose(agent_slice_values[j][slice-1], np.max(agent_slice_values[j]),rtol=0,atol=1e-10) and \
                (agent_slice_values[0][slice-1] <= alpha)):
                print(f"{agent_slice_values[i][slice-1]},{np.max(agent_slice_values[i])}")
                print(f"{agent_slice_values[j][slice-1]},{np.max(agent_slice_values[j])}")
                print(f"{division.left},{division.middle},{division.right}")
                print("a")
                return True
            else:
                return False

In [17]:
div = FourAgentPortion(4.440892098500626e-16,4.440892098500626e-16,0.9999999999999889)
agents_number = 4
slices_number = 4
agent_slice_values = np.zeros((agents_number,slices_number))
for k in range(agents_number):
    agent_slice_values[k] = slice_values(k, preferences, div, 4, epsilon)

NameError: name 'FourAgentPortion' is not defined

In [ ]:
agent_slice_values[1]

In [ ]:
value_query(1, preferences, div.middle, div.right, epsilon)

In [ ]:
left_slice_value = np.array([value_query(1, preferences, 0, div.left, 
                                         epsilon)])
#middle_slice_values = find_middle_slice_values(agent, prefs, division, 
                                              # agents_number, epsilon)
right_slice_value = np.array([value_query(1, preferences, div.right, 1, 
                                          epsilon)])
slice_two_value = value_query(1, preferences, div.left, 
                              div.middle, epsilon)
slice_three_value = value_query(1, preferences, div.middle, 
                                div.right, epsilon)
middle_slice_values = np.array([slice_two_value, slice_two_value])
check = np.concatenate([left_slice_value, middle_slice_values, 
                       right_slice_value])

In [18]:
slice_three_value

NameError: name 'slice_three_value' is not defined

In [19]:
middle_slice_values

NameError: name 'middle_slice_values' is not defined

In [20]:
check

NameError: name 'check' is not defined

In [21]:
slice_values(1, preferences, div, 4, epsilon)

NameError: name 'slice_values' is not defined

In [22]:
def condition_b_slice_one_two_preferred(prefs, alpha, epsilon, return_division = False):
    right_cut = cut_query(0, prefs, 1, alpha, epsilon, end_cut = False)
    middle_cut = cut_query(0, prefs, right_cut, alpha, epsilon, end_cut = False)
    for i in range(1,4):
        left_cut = bisection_cut_query(i, prefs, 0, middle_cut, epsilon)
        division = FourAgentPortion(left_cut, middle_cut, right_cut)
        if check_valid_division(division) == False:
            continue
        check_value = condition_b_check([1,2], prefs, alpha, division, epsilon)
        if (check_value == True) and (return_division == True):
            return division
        if (check_value == True) and (return_division == False):
            return check_value
        else:
            continue
    return False

In [23]:
def condition_b_slice_two_three_preferred(prefs, alpha, epsilon, return_division = False):
    left_cut = cut_query(0, prefs, 0, alpha, epsilon, end_cut = True)
    right_cut = cut_query(0, prefs, 1, alpha, epsilon, end_cut = False)
    for i in range(1,4):
        middle_cut = bisection_cut_query(i, prefs, left_cut, right_cut, epsilon)
        division = FourAgentPortion(left_cut, middle_cut, right_cut)
        if check_valid_division(division) == False:
            continue
        check_value = condition_b_check([2,3], prefs, alpha, division, epsilon)
        if (check_value == True) and (return_division == True):
            return division
        if (check_value == True) and (return_division == False):
            return check_value
        else:
            continue
    return False

In [24]:
def condition_b_slice_three_four_preferred(prefs, alpha, epsilon, return_division = False):
    left_cut = cut_query(0, prefs, 0, alpha, epsilon, end_cut = True)
    middle_cut = cut_query(0, prefs, left_cut, alpha, epsilon, end_cut = True)
    for i in range(1,4):
        right_cut = bisection_cut_query(i, prefs, middle_cut, 1, epsilon)
        division = FourAgentPortion(left_cut, middle_cut, right_cut)
        if check_valid_division(division) == False:
            continue
        check_value = condition_b_check([3,4], prefs, alpha, division, epsilon)
        if (check_value == True) and (return_division == True):
            return division
        if (check_value == True) and (return_division == False):
            return check_value
        else:
            continue
    return False

In [25]:
def condition_b_slice_one_three_preferred(prefs, alpha, epsilon, return_division = False):
    right_cut = cut_query(0, prefs, 1, alpha, epsilon, end_cut = False)
    for i in range(1,4):
        left_cut, middle_cut = \
            one_apart_slice_cuts(i, prefs, alpha, 0, right_cut, epsilon)
        division = FourAgentPortion(left_cut, middle_cut, right_cut)
        if check_valid_division(division) == False:
            continue
        check_value = condition_b_check([1,3], prefs, alpha, division, epsilon)
        if (check_value == True) and (return_division == True):
            return division
        if (check_value == True) and (return_division == False):
            return check_value
        else:
            continue
    return False

In [26]:
def condition_b_slice_two_four_preferred(prefs, alpha, epsilon, return_division = False):
    left_cut = cut_query(0, prefs, 0, alpha, epsilon, end_cut = True)
    for i in range(1,4):
        middle_cut, right_cut = \
            one_apart_slice_cuts(i, prefs, alpha, left_cut, 1, epsilon)
        division = FourAgentPortion(left_cut, middle_cut, right_cut)
        if check_valid_division(division) == False:
            continue
        check_value = condition_b_check([3,4], prefs, alpha, division, epsilon)
        if (check_value == True) and (return_division == True):
            return division
        if (check_value == True) and (return_division == False):
            return check_value
        else:
            continue
    return False

In [27]:
def one_apart_slice_cuts(indifferent_agent, prefs, alpha, left_bound, 
                         right_bound, epsilon):
    leftmost_unknown_cut = \
        non_adjacent_slice_cuts_update(indifferent_agent, prefs, 
                                       alpha, left_bound, right_bound, epsilon,
                                       leftmost_cut_bounds_one_apart_update)
    rightmost_unknown_cut = \
        non_adjacent_slice_cuts_update(indifferent_agent, prefs, 
                                       alpha, left_bound, right_bound, epsilon,
                                       rightmost_cut_bounds_one_apart_update)
    return leftmost_unknown_cut, rightmost_unknown_cut

In [28]:
def non_adjacent_slice_cuts_update(indifferent_agent, prefs, alpha, left_bound, 
                                right_bound, epsilon, cut_bounds_update):
    cut_bounds = Bounds(left_bound, right_bound)
    while (cut_bounds.upper // epsilon) != (cut_bounds.lower // epsilon):
        cut_bounds = \
            cut_bounds_update(indifferent_agent, prefs, 
                              cut_bounds, alpha, left_bound,
                              right_bound, epsilon)
    cut_epsilon_interval = find_epsilon_interval(cut_bounds, epsilon)
    while abs(cut_bounds.upper - cut_bounds.lower) > 1e-15:
        cut_bounds = cut_bounds_update(indifferent_agent, prefs, 
                                       cut_bounds, alpha, left_bound,
                                       right_bound, epsilon)
    return cut_bounds.midpoint()


In [29]:
def leftmost_cut_bounds_one_apart_update(agent, prefs, leftmost_cut_bounds, 
                                         alpha, left_bound, right_bound,
                                         epsilon):
    leftmost_cut = leftmost_cut_bounds.midpoint()
    left_segment_value = value_query(agent, prefs, left_bound, leftmost_cut,
                                     epsilon)
    rightmost_cut = cut_query(0, prefs, leftmost_cut, alpha, epsilon, 
                              end_cut = True)
    right_segment_value = value_query(agent, prefs, rightmost_cut, right_bound,
                                      epsilon)
    leftmost_cut_bounds = bounds_shift(left_segment_value, right_segment_value, 
                                       leftmost_cut_bounds)
    return leftmost_cut_bounds

In [30]:
def rightmost_cut_bounds_one_apart_update(agent, prefs, rightmost_cut_bounds, 
                                          alpha, left_bound, right_bound, 
                                          epsilon):
    rightmost_cut = rightmost_cut_bounds.midpoint()
    right_segment_value = value_query(agent, prefs, rightmost_cut, 
                                      right_bound, epsilon)
    leftmost_cut = cut_query(0, prefs, rightmost_cut, alpha, epsilon, 
                             end_cut = False)
    left_segment_value = value_query(agent, prefs, left_bound, 
                                     leftmost_cut, epsilon)
    rightmost_cut_bounds = bounds_shift(left_segment_value, right_segment_value, 
                                        rightmost_cut_bounds)
    return rightmost_cut_bounds

In [31]:
def condition_b_slice_one_four_preferred(prefs, alpha, epsilon, return_division = False):
    for i in range(1,4):
        left_cut, middle_cut, right_cut = \
            two_apart_slice_cuts(i, prefs, alpha, 0, 1, epsilon)
        division = FourAgentPortion(left_cut, middle_cut, right_cut)
        if check_valid_division(division) == False:
            continue
        check_value = condition_b_check([1,4], prefs, alpha, division, epsilon)
        if (check_value == True) and (return_division == True):
            return division
        if (check_value == True) and (return_division == False):
            return check_value
        else:
            continue
    return False

In [32]:
def check_valid_division(division):
    if ((division.right >= division.middle) and (division.middle >= division.left)):
        return True
    else:
        return False

In [33]:
def two_apart_slice_cuts(indifferent_agent, prefs, alpha, left_bound, 
                         right_bound, epsilon):
    left_cut = \
        non_adjacent_slice_cuts_update(indifferent_agent, prefs, alpha, 0, 1, 
                                       epsilon, left_cut_bounds_two_apart_update)
    middle_cut = \
        non_adjacent_slice_cuts_update(indifferent_agent, prefs, alpha, 0, 1, 
                                       epsilon, middle_cut_bounds_two_apart_update)
    
    right_cut = \
        non_adjacent_slice_cuts_update(indifferent_agent, prefs, alpha, 0, 1, 
                                       epsilon, right_cut_bounds_two_apart_update)
    return left_cut, middle_cut, right_cut

In [34]:
def left_cut_bounds_two_apart_update(agent, prefs, 
                                     left_cut_bounds, alpha, left_bound,
                                     right_bound, epsilon):
    left_cut = left_cut_bounds.midpoint()
    middle_cut = cut_query(0, prefs, left_cut, alpha, epsilon, end_cut = True)
    right_cut = cut_query(0, prefs, middle_cut, alpha, epsilon, end_cut = True)
    left_segment_value = value_query(agent, prefs, 0, left_cut, epsilon)
    right_segment_value = value_query(agent, prefs, right_cut, 1, epsilon)
    left_cut_bounds = bounds_shift(left_segment_value, right_segment_value, 
                                   left_cut_bounds)
    return left_cut_bounds 

In [35]:
def middle_cut_bounds_two_apart_update(agent, prefs, 
                                       middle_cut_bounds, alpha, left_bound,
                                       right_bound, epsilon):
    middle_cut = middle_cut_bounds.midpoint()
    left_cut = cut_query(0, prefs, middle_cut, alpha, epsilon, end_cut = False)
    right_cut = cut_query(0, prefs, middle_cut, alpha, epsilon, end_cut = True)
    left_segment_value = value_query(agent, prefs, 0, left_cut, epsilon)
    right_segment_value = value_query(agent, prefs, right_cut, 1, epsilon)
    middle_cut_bounds = bounds_shift(left_segment_value, right_segment_value, 
                                     middle_cut_bounds)
    return middle_cut_bounds 

In [36]:
def right_cut_bounds_two_apart_update(agent, prefs, 
                                      right_cut_bounds, alpha, left_bound,
                                      right_bound, epsilon):
    right_cut = right_cut_bounds.midpoint()
    middle_cut = cut_query(0, prefs, right_cut, alpha, epsilon, end_cut = False)
    left_cut = cut_query(0, prefs, middle_cut, alpha, epsilon, end_cut = False)
    left_segment_value = value_query(agent, prefs, 0, left_cut, epsilon)
    right_segment_value = value_query(agent, prefs, right_cut, 1, epsilon)
    right_cut_bounds = bounds_shift(left_segment_value, right_segment_value, 
                                    right_cut_bounds)
    return right_cut_bounds  

In [37]:
#need to change equality to range.
def condition_b_check(slices, prefs, alpha, division, epsilon):
    agents_number = 4
    slices_number = 4
    agent_slice_values = np.zeros((agents_number,slices_number))
    slice_check = np.zeros(2)
    for k in range(agents_number):
        agent_slice_values[k] = slice_values(k, prefs, division, 4, epsilon)
    for s in range(2):
        for i in range(1, agents_number):
            for j in range(1, agents_number):
                if j == i:
                    continue
                if ((agent_slice_values[i][slices[s]-1] == np.max(agent_slice_values[i])) and \
                    (agent_slice_values[j][slices[s]-1] == np.max(agent_slice_values[j]))):
                    slice_check[s] = True
    if (slice_check[0] == True and slice_check[1] == True):
        return True
    else: 
        return False

In [38]:
def condition_b_check(slices, prefs, alpha, division, epsilon):
    agents_number = 4
    slices_number = 4
    agent_slice_values = np.zeros((agents_number,slices_number))
    slice_check = np.zeros(2)
    for k in range(agents_number):
        agent_slice_values[k] = slice_values(k, prefs, division, 4, epsilon)
    for s in range(2):
        for i in range(1, agents_number):
            for j in range(1, agents_number):
                if j == i:
                    continue
                if (np.isclose(agent_slice_values[i][slices[s]-1], np.max(agent_slice_values[i]),rtol=0,atol=1e-10) and \
                    np.isclose(agent_slice_values[j][slices[s]-1], np.max(agent_slice_values[j]),rtol=0,atol=1e-10)):
                    print(f"{agent_slice_values[i][slices[s]-1]},{np.max(agent_slice_values[i])}")
                    print(f"{agent_slice_values[j][slices[s]-1]},{np.max(agent_slice_values[j])}")
                    print(f"{division.left},{division.middle},{division.right}")
                    print("b")
                    slice_check[s] = True
    if (slice_check[0] == True and slice_check[1] == True):
        return True
    else: 
        return False

In [39]:
slices = [0,1]
for s in slices:
    print(s)

0
1


In [40]:
for i in range(1,4):
    print(i)

1
2
3


In [41]:
def check_equipartition_envy_free_four_agents(prefs, alpha, agents_number, epsilon):
    left_cut = cut_query(0, preferences, 0, alpha, epsilon)
    middle_cut = cut_query(0, preferences, left_cut, alpha, epsilon)
    right_cut = cut_query(0, preferences, middle_cut, alpha, epsilon)
    division = FourAgentPortion(left_cut, middle_cut, right_cut)
    agent_one_slice_values = slice_values(1, prefs, division, agents_number, epsilon)
    agent_two_slice_values = slice_values(2, prefs, division, agents_number, epsilon)
    agent_three_slice_values = slice_values(3, prefs, division, agents_number, epsilon)
    is_envy_free = check_unique_preferences_four_agent(agent_one_slice_values,
                                                       agent_two_slice_values,
                                                       agent_three_slice_values)
    return is_envy_free

In [42]:
def check_unique_preferences_four_agent(agent_one_slice_values,
                                        agent_two_slice_values,
                                        agent_three_slice_values):
    for i in range(4):
        for j in range(4):
            for k in range(4):
                if (k == j) or (k == i) or (j == i):
                    continue
                if  (agent_one_slice_values[i] == np.max(agent_one_slice_values)) and \
                    (agent_two_slice_values[i] == np.max(agent_two_slice_values)) and \
                    (agent_three_slice_values[i] == np.max(agent_three_slice_values)):
                    return True
    return False

In [43]:
def check_equipartition_envy_free_three_agents(prefs, alpha, 
                                               agents_number, epsilon):
    left_cut = cut_query(0, preferences, 0, alpha, epsilon)
    right_cut = cut_query(0, preferences, left_cut, alpha, epsilon)
    division = ThreeAgentPortion(left_cut,right_cut)
    agent_one_slice_values = slice_values(1, prefs, division, agents_number,
                                          epsilon)
    agent_two_slice_values = slice_values(2, prefs, division, agents_number,
                                          epsilon)
    is_envy_free = check_unique_preferences_three_agent(agent_one_slice_values,
                                                        agent_two_slice_values)
    return is_envy_free
            

In [44]:
def check_unique_preferences_three_agent(agent_one_slice_values,
                                         agent_two_slice_values):
    for i in range(3):
        for j in range(3):
            if j == i:
                continue
            if  ((agent_one_slice_values[i] == np.max(agent_one_slice_values)) and \
                 (agent_two_slice_values[j] == np.max(agent_two_slice_values))):
                return True
    return False

In [45]:
def division_three_agents(prefs, alpha, epsilon):
    if check_invariant_three_agents(prefs, alpha, epsilon)[1] == 1:
        right_cut = cut_query(0, preferences, 1, alpha, epsilon, end_cut = False)
        left_cut = cut_query(0, preferences, right_cut, alpha, 
                             epsilon, end_cut = False)
    if check_invariant_three_agents(prefs, alpha, epsilon)[1] == 2:
        left_cut = cut_query(0, preferences, 0, alpha, epsilon)
        right_cut = cut_query(0, preferences, 1, alpha, epsilon, end_cut = False)
        
    if check_invariant_three_agents(prefs, alpha, epsilon)[1] == 3:
        left_cut = cut_query(0, preferences, 0, alpha, epsilon)
        right_cut = cut_query(0, preferences, left_cut, alpha, epsilon)
    division = ThreeAgentPortion(left_cut,right_cut)
    return division

In [46]:
def check_invariant_three_agents(prefs, alpha, epsilon):
    if invariant_three_agents_slice_one_preferred(prefs, alpha, epsilon) == True:
        return True, 1
    if invariant_three_agents_slice_two_preferred(prefs, alpha, epsilon) == True:
        return True, 2
    if invariant_three_agents_slice_three_preferred(prefs, alpha, epsilon) == True:
        return True, 3
    else:
        return False, 0

In [47]:
def invariant_three_agents_slice_one_preferred(prefs, alpha, epsilon):
    right_cut = cut_query(0, prefs, 1, alpha, epsilon, end_cut = False)
    left_cut = cut_query(0, prefs, right_cut, alpha, 
                         epsilon, end_cut = False)
    division = ThreeAgentPortion(left_cut,right_cut)
    return invariant_three_agent_check(1, prefs, division, epsilon)
    

In [48]:
def invariant_three_agents_slice_two_preferred(prefs, alpha, epsilon):
    left_cut = cut_query(0, prefs, 0, alpha, epsilon)
    right_cut = cut_query(0, prefs, 1, alpha, epsilon, end_cut = False)
    division = ThreeAgentPortion(left_cut,right_cut)
    return invariant_three_agent_check(2, prefs, division, epsilon)



In [49]:
def invariant_three_agents_slice_three_preferred(prefs, alpha, epsilon):
    left_cut = cut_query(0, prefs, 0, alpha, epsilon)
    right_cut = cut_query(0, prefs, left_cut, alpha, epsilon)
    division = ThreeAgentPortion(left_cut,right_cut)
    return invariant_three_agent_check(3, prefs, division, epsilon)

In [50]:
def invariant_three_agent_check(slice, prefs, division, epsilon):
    agent_one_slice_values = slice_values(1, prefs, division, 3, epsilon)
    agent_two_slice_values = slice_values(2, prefs, division, 3, epsilon)
    
    if  ((agent_one_slice_values[slice-1] == np.max(agent_one_slice_values)) and \
        (agent_two_slice_values[slice-1] == np.max(agent_two_slice_values))):
        return True
    else:
        return False

In [51]:
def slice_values(agent, prefs, division, agents_number, epsilon):
    check_valid_agents_value(agents_number)
    left_slice_value = np.array([value_query(agent, prefs, 0, division.left, 
                                             epsilon)])
    middle_slice_values = find_middle_slice_values(agent, prefs, division, 
                                                   agents_number, epsilon)
    right_slice_value = np.array([value_query(agent, prefs, division.right, 1, 
                                              epsilon)])
    return np.concatenate([left_slice_value, middle_slice_values, 
                           right_slice_value])

In [52]:
def find_middle_slice_values(agent, prefs, division, agents_number, epsilon):
    if agents_number == 3:
        middle_slice_values = np.array([value_query(agent, prefs, division.left, 
                                                    division.right, epsilon)])
    if agents_number == 4:
        slice_two_value = value_query(agent, prefs, division.left, 
                                      division.middle, epsilon)
        slice_three_value = value_query(agent, prefs, division.middle, 
                                      division.right, epsilon)
        middle_slice_values = np.array([slice_two_value, slice_three_value])
    return middle_slice_values

In [53]:
def check_valid_agents_value(agents_number):
    assert agents_number == 3 or agents_number == 4, \
        "invalid number of agents. Please input either 3 or 4."

In [54]:
def compute_equipartition(prefs, agents_number, epsilon):
    left_cut_bounds = find_cut_epsilon_interval(prefs, agents_number, epsilon,
                                                left_cut_bounds_update)
    if agents_number == 3:
        middle_cut_bounds = None
    if agents_number == 4:
        middle_cut_bounds = \
            find_cut_epsilon_interval(prefs, agents_number, epsilon,
                                      middle_cut_bounds_update)
    right_cut_bounds = find_cut_epsilon_interval(prefs, agents_number, epsilon,
                                                 right_cut_bounds_update)
    
    equipartition = \
        exact_equipartition_cuts(prefs, left_cut_bounds, middle_cut_bounds,
                                 right_cut_bounds, agents_number, epsilon)
    return equipartition

In [55]:
#make agents_number optional.
def find_cut_epsilon_interval(prefs, agents_number, epsilon, cut_bounds_update):
    cut_bounds = Bounds(0, 1)
    while (cut_bounds.upper // epsilon) != (cut_bounds.lower // epsilon):
        cut_bounds = cut_bounds_update(prefs, cut_bounds, agents_number, epsilon)
    cut_epsilon_interval = find_epsilon_interval(cut_bounds, epsilon)
    return cut_epsilon_interval

In [56]:
def left_cut_bounds_update(prefs, left_cut_bounds, agents_number, epsilon):
    left_cut = left_cut_bounds.midpoint()
    left_segment_value = value_query(0, prefs, 0, left_cut, epsilon)
    if agents_number == 3:
        right_segment_value = \
            left_cut_bounds_right_segment_value_three_agent(prefs, left_cut, 
                                                            left_segment_value,
                                                            epsilon)
    if agents_number == 4:
        right_segment_value = \
            left_cut_bounds_right_segment_value_four_agent(prefs, left_cut, 
                                                           left_segment_value,
                                                           epsilon)
    left_cut_bounds = bounds_shift(left_segment_value, right_segment_value, 
                                   left_cut_bounds)
    return left_cut_bounds

In [57]:
def left_cut_bounds_right_segment_value_three_agent(prefs, left_cut, 
                                                    left_segment_value,
                                                    epsilon):
    right_cut = cut_query(0, prefs, left_cut, left_segment_value, 
                        epsilon, end_cut = True)
    right_segment_value = value_query(0, prefs, right_cut, 1, epsilon)
    return right_segment_value

In [58]:
def left_cut_bounds_right_segment_value_four_agent(prefs, left_cut, 
                                                   left_segment_value,
                                                   epsilon):
    middle_cut = cut_query(0, prefs, left_cut, left_segment_value, 
                               epsilon, end_cut = True)
    right_cut = cut_query(0, prefs, middle_cut, left_segment_value, 
                              epsilon, end_cut = True)
    right_segment_value = value_query(0, prefs, right_cut, 1, epsilon)
    return right_segment_value

In [59]:
def middle_cut_bounds_update(prefs, middle_cut_bounds, agents_number, epsilon):
    middle_cut = middle_cut_bounds.midpoint()
    left_cut = bisection_cut_query(0, prefs, 0, middle_cut, epsilon)
    right_cut = bisection_cut_query(0, prefs, middle_cut, 1, epsilon)
    left_segment_value = value_query(0, prefs, 0, left_cut, epsilon)
    right_segment_value = value_query(0, prefs, right_cut, 1, epsilon)
    middle_cut_bounds = bounds_shift(left_segment_value, right_segment_value, 
                                     middle_cut_bounds)
    return middle_cut_bounds

In [60]:
def bisection_cut_query(agent, prefs, start, end, epsilon):
    bisection_cut_bounds = Bounds(start, end)
    while abs(bisection_cut_bounds.upper - bisection_cut_bounds.lower) > 1e-15:
        bisection_cut_bounds = \
            bisection_cut_bounds_update(agent, prefs, start, end,
                                        bisection_cut_bounds, epsilon)
    bisection_cut = bisection_cut_bounds.midpoint()
    return bisection_cut

In [61]:
def bisection_cut_bounds_update(agent, prefs, start, end, 
                                bisection_cut_bounds, epsilon):
    bisection_cut = bisection_cut_bounds.midpoint()
    left_segment_value = value_query(agent, prefs, start, bisection_cut, epsilon)
    right_segment_value = value_query(agent, prefs, bisection_cut, end, epsilon)
    bisection_cut_bounds = bounds_shift(left_segment_value, right_segment_value, 
                                        bisection_cut_bounds) 
    return bisection_cut_bounds


In [62]:
def right_cut_bounds_update(prefs, right_cut_bounds, agents_number, epsilon):
    right_cut = right_cut_bounds.midpoint()
    right_segment_value = value_query(0, prefs, right_cut, 1, epsilon)
    if agents_number == 3:
        left_segment_value = \
            right_cut_bounds_left_segment_value_three_agent(prefs, right_cut, 
                                                            right_segment_value,
                                                            epsilon)
    if agents_number == 4:
        left_segment_value = \
            right_cut_bounds_left_segment_value_four_agent(prefs, right_cut, 
                                                            right_segment_value,
                                                            epsilon)
    right_cut_bounds = bounds_shift(left_segment_value, right_segment_value, 
                                    right_cut_bounds)
    return right_cut_bounds

In [63]:
def right_cut_bounds_left_segment_value_three_agent(prefs, right_cut, 
                                                    right_segment_value,
                                                    epsilon):
    left_cut = cut_query(0, prefs, right_cut, right_segment_value, 
                        epsilon, end_cut = False)
    left_segment_value = value_query(0, prefs, 0, left_cut, epsilon)
    return left_segment_value

In [64]:
def right_cut_bounds_left_segment_value_four_agent(prefs, right_cut, 
                                                   right_segment_value,
                                                   epsilon):
    middle_cut = cut_query(0, prefs, right_cut, right_segment_value, 
                        epsilon, end_cut = False)
    left_cut = cut_query(0, prefs, middle_cut, right_segment_value, 
                        epsilon, end_cut = False)
    left_segment_value = value_query(0, prefs, 0, left_cut, epsilon)
    return left_segment_value

In [65]:
def find_epsilon_interval(bounds, epsilon):
    value_within_interval = bounds.midpoint()
    lower_bound_of_interval = (value_within_interval // epsilon) * epsilon
    upper_bound_of_interval = lower_bound_of_interval + epsilon 
    epsilon_interval = Bounds(lower_bound_of_interval, upper_bound_of_interval)
    return epsilon_interval

In [66]:
def exact_equipartition_cuts(prefs, left_cut_bounds, middle_cut_bounds, 
                             right_cut_bounds, agents_number, epsilon):
    left_cut = equipartition_cut(prefs, left_cut_bounds, agents_number, epsilon,
                                 left_cut_bounds_update)
    right_cut= equipartition_cut(prefs, right_cut_bounds, agents_number, epsilon,
                                 right_cut_bounds_update)
    if agents_number == 3:
        equipartition = ThreeAgentPortion(left_cut, right_cut)
    if agents_number == 4:
        middle_cut= equipartition_cut(prefs, middle_cut_bounds, agents_number, 
                                      epsilon, middle_cut_bounds_update)
        equipartition = FourAgentPortion(left_cut, middle_cut, right_cut)
    alpha = value_query(0, preferences, 0, left_cut, epsilon)
    return equipartition, alpha
    

In [67]:
def equipartition_cut(prefs, cut_bounds, agent_numbers,
                      epsilon, cut_bounds_update):
    while abs(cut_bounds.upper - cut_bounds.lower) > 1e-15:
        cut_bounds = cut_bounds_update(prefs, cut_bounds, agent_numbers, epsilon)
    return cut_bounds.midpoint()

In [68]:
def bounds_shift(left_slice_value, right_slice_value, cut_bounds):
    cut = cut_bounds.midpoint()
    if left_slice_value >= right_slice_value:
        cut_bounds.upper = cut
    if left_slice_value < right_slice_value:
        cut_bounds.lower = cut
    return cut_bounds

In [69]:
right_cut_bounds = find_right_cut_epsilon_interval(preferences, epsilon)
right_cut = equipartition_right_cut_three_agents(preferences, right_cut_bounds,
                                                epsilon)
value_query(0, preferences, right_cut, 1, epsilon)/ \
value_query(0, preferences, 0, right_cut, epsilon)

NameError: name 'find_right_cut_epsilon_interval' is not defined

In [70]:
left_cut_bounds = find_left_cut_epsilon_interval(preferences, epsilon)
left_cut = equipartition_left_cut_three_agents(preferences, left_cut_bounds,
                                                epsilon)
value_query(0, preferences, 0, left_cut, epsilon)/ \
value_query(0, preferences, left_cut, 1, epsilon)


NameError: name 'find_left_cut_epsilon_interval' is not defined

In [71]:
#Must add functionality that returns if there is no cut.
def cut_query(agent, prefs, initial_cut, value, epsilon, end_cut = True):
    if end_cut == True:
        queried_cut = end_cut_query(agent, prefs, initial_cut, value, epsilon)
    else:
        queried_cut = start_cut_query(agent, prefs, initial_cut, value, epsilon)
    return queried_cut

In [72]:
def end_cut_query(agent, prefs, start, value, epsilon):
    end_cut_bounds = Bounds(start, 1)
    while abs(end_cut_bounds.upper - end_cut_bounds.lower) > 1e-15:
        end_cut_bounds = end_cut_bounds_update(prefs, start, end_cut_bounds, 
                                               value, epsilon)
    end_cut = end_cut_bounds.midpoint()
    return end_cut

In [73]:
def end_cut_bounds_update(prefs, start, end_cut_bounds, 
                          value, epsilon):
    end_cut = end_cut_bounds.midpoint()
    queried_value = value_query(0, prefs, start, end_cut, epsilon)
    if queried_value <= value:
        end_cut_bounds.lower  = end_cut
    if queried_value > value:
        end_cut_bounds.upper = end_cut
    return end_cut_bounds

In [74]:
def start_cut_query(agent, prefs, end, value, epsilon):
    start_cut_bounds = Bounds(0, end)
    while abs(start_cut_bounds.upper - start_cut_bounds.lower) > 1e-15:
        start_cut_bounds = start_cut_bounds_update(prefs, end, start_cut_bounds, 
                                                   value, epsilon)
    start_cut = start_cut_bounds.midpoint()
    return start_cut

In [75]:
def start_cut_bounds_update(prefs, end, start_cut_bounds, 
                            value, epsilon):
    start_cut = start_cut_bounds.midpoint()
    queried_value = value_query(0, prefs, start_cut, end, epsilon)
    if queried_value <= value:
        start_cut_bounds.upper  = start_cut
    if queried_value > value:
        start_cut_bounds.lower = start_cut
    return start_cut_bounds

In [76]:
#Remember to scale by L at end.
def one_lipschitz(prefs, cakeSize):
    prefs = change_bounds(prefs, cakeSize)
    #prefs, normalizationConstants = normalization(prefs)
    prefs = normalization(prefs)
    return prefs#, normalizationConstants

In [77]:
def change_bounds(prefs, cakeSize):
    for agents in prefs:
        for segments in agents:
            segments['start'] /= cakeSize
            segments['end'] /= cakeSize
    return prefs
        

In [78]:
'''
Ensures that each agents values the
'''
def normalization(prefs):
    '''
    Ensures that each agents values the
    '''
    #Need to change.
    agents = len(prefs)
    normalization_constants = np.zeros(agents)
    for i in range(agents):
        normalization_constants[i] = value_query_initial(i, prefs, 0, 1)
        for segments in prefs[i]:
            segments['startValue'] /= normalization_constants[i]
            segments['endValue'] /= normalization_constants[i]
    return prefs#, normalizationConstants

In [79]:
'''
Linear interpolation on epsilon grid.
'''
def value_query(agent, prefs, start, end, epsilon):
    start_bounds, end_bounds = piecewise_linear_bounds(start, end, epsilon)
    
    if start_bounds.upper - start >= end - end_bounds.lower:
        return value_query_variant_one(agent, prefs, start, end, epsilon)
    if start_bounds.upper - start < end - end_bounds.lower:
        return value_query_variant_two(agent, prefs, start, end, epsilon)

In [80]:
def value_query_variant_one(agent, prefs, start, end, epsilon):
    start_bounds, end_bounds = piecewise_linear_bounds(start, end, epsilon)
    queries = intermediate_queries_variant_one(agent, prefs, start_bounds, 
                                            end_bounds, epsilon)
    component_one = (((start_bounds.upper - start) - (end - end_bounds.lower)) / 
                    epsilon) * queries[0]
    component_two = ((end - end_bounds.lower) / epsilon) * queries[1]
    component_three = ((start - start_bounds.lower) / epsilon) * queries[2]
    return component_one + component_two + component_three

In [81]:
def value_query_variant_two(agent, prefs, start, end, epsilon):
    start_bounds, end_bounds = piecewise_linear_bounds(start, end, epsilon)
    queries = intermediate_queries_variant_two(agent, prefs, start_bounds, 
                                               end_bounds, epsilon)
    component_one = (((end - end_bounds.lower) - (start_bounds.upper - start)) / 
                    epsilon) * queries[0]
    component_two = ((start_bounds.upper - start) / epsilon) * queries[1]
    component_three = ((end_bounds.upper - end) / epsilon) * queries[2]
    return component_one + component_two + component_three

In [82]:
def piecewise_linear_bounds(start, end, epsilon):
    if start != 1:
        start_lower_bound = (start // epsilon) * epsilon
        start_upper_bound = start_lower_bound + epsilon 
    else:
        start_lower_bound = 1 - epsilon
        start_upper_bound = 1
    if end != 1:
        end_lower_bound = (end // epsilon) * epsilon
        end_upper_bound = end_lower_bound + epsilon
    else:
        end_lower_bound = 1 - epsilon
        end_upper_bound = 1

    start_bounds = Bounds(start_lower_bound, start_upper_bound)
    end_bounds = Bounds(end_lower_bound, end_upper_bound)

    return start_bounds, end_bounds

In [83]:
def intermediate_queries_variant_one(agent, prefs, start_bounds, 
                                     end_bounds, epsilon):
    query_one = value_query_hungry(agent, prefs, start_bounds.lower, 
                                end_bounds.lower, epsilon)
    query_two = value_query_hungry(agent, prefs, start_bounds.lower, 
                                end_bounds.upper, epsilon)
    query_three = value_query_hungry(agent, prefs, start_bounds.upper, 
                                  end_bounds.lower, epsilon)
    return query_one, query_two, query_three

In [84]:
def intermediate_queries_variant_two(agent, prefs, start_bounds, 
                                     end_bounds, epsilon):
    query_one = value_query_hungry(agent, prefs, start_bounds.upper, 
                                   end_bounds.upper, epsilon)
    query_two = value_query_hungry(agent, prefs, start_bounds.lower, 
                                   end_bounds.upper, epsilon)
    query_three = value_query_hungry(agent, prefs, start_bounds.upper, 
                                     end_bounds.lower, epsilon)
    return query_one, query_two, query_three

In [85]:
def value_query_hungry(agent, prefs, start, end, epsilon):
    initial_value = value_query_initial(agent, prefs, start, end)
    value = initial_value / 2 + epsilon * (end - start)
    return value

In [86]:
def value_query_initial(agent, prefs, start, end):
    check_valid_bounds(start,end)
    if end <= start:
        value = 0
    else:
        value = one_sided_query(agent, prefs, end) - \
                one_sided_query(agent, prefs, start)
    return value
    

In [87]:
def check_valid_bounds(start,end):
    assert (start >= 0 and start <= 1 and end >= 0 and end <= 1), \
        "invalid bounds. start and end should be between 0 and 1."

In [88]:
def one_sided_query(agent, prefs, end):
    segments = np.size(prefs[agent])
    value = 0
    for i in range(segments):
        if end > prefs[agent][i]['end']:
            value += find_full_value(prefs[agent][i])
        if end <= prefs[agent][i]['end']:
            value += find_partial_value(prefs[agent][i], end)
            return value

In [89]:
def find_full_value(segment):
    segment_width = segment['end'] - segment['start']
    if segment['startValue'] == segment['endValue']:
        value = segment['startValue'] * segment_width
        return value
    if segment['startValue'] != segment['endValue']:
        value = 0.5 * (segment['startValue'] + segment['endValue']) * segment_width
        return value

In [90]:
def find_partial_value(segment, partial_segment_end):
    segment_width = partial_segment_end - segment['start']
    partial_segment_end_value = interpolate(segment, partial_segment_end)
    if segment['startValue'] == segment['endValue']:
        value = segment['startValue'] * segment_width
        return value
    if segment['startValue'] != segment['endValue']:
        value = 0.5 * (segment['startValue'] + partial_segment_end_value) * \
                segment_width
        return value

In [91]:
'''
Uses the linear interpolation formula to find the associated y-coordinate for a 
given x-coordinate on a line between two points with known x and y coordinates.
'''
def interpolate(segment, x_coordinate):
    if segment['startValue'] == segment['endValue']:
        y_coordinate = segment['startValue']
        return y_coordinate
    if segment['startValue'] != segment['endValue']:
        y_coordinate = ((segment['startValue'] * (segment['end'] - x_coordinate) +
                         segment['endValue'] * (x_coordinate - segment['start'])) / 
                        (segment['end'] - segment['start']))                
        return y_coordinate

In [92]:
class Bounds:
    def __init__(self, lower, upper):
        self.lower = lower
        self.upper = upper

    def midpoint(self):
        return (self.lower + self.upper) / 2


In [93]:
class ThreeAgentPortion:
    def __init__(self, left_cut, right_cut):
        self.left = left_cut
        self.right = right_cut

In [94]:
class FourAgentPortion:
    def __init__(self, left_cut, middle_cut, right_cut):
        self.left = left_cut
        self.middle = middle_cut
        self.right = right_cut